spring:
  application:
    name: bulk-api

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=apa;encrypt=false;trustServerCertificate=true
    username: sa
    password: P@ssw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 2

bulk-api:
  external-api:
    base-url: "http://localhost:8081"
  processing:
    thread-pool-size: 50
    batch-size: 100
    rate-limit: 1000

resilience4j:
  circuitbreaker:
    instances:
      signalApi:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      signalApi:
        max-attempts: 5
        wait-duration: 10s
